Huggingface:
  key: "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"
  model: "ollama"
  timeout: 30
  temperature: 0.7
OpenAI:
  key: "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"
  model: "openai/gpt-4o-mini"
  timeout: 30
  temperature: 0.7
MLModel_path: "./ML_models/models/bidirectionalLSTM.h5"
data_path: "./data/MITVolume_cleaned.csv"